// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0bBooM-u0KjypX5p10amF3QVw4lMD_Sw',
    appId: '1:1098879051348:web:5fd553b773608e4e4eafc1',
    messagingSenderId: '1098879051348',
    projectId: 'assistant-app-iitu',
    authDomain: 'assistant-app-iitu.firebaseapp.com',
    storageBucket: 'assistant-app-iitu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd8K7uEP-ZS2Jep3Xi5ZWvdVysSAepQdI',
    appId: '1:1098879051348:android:710381acbd67bb944eafc1',
    messagingSenderId: '1098879051348',
    projectId: 'assistant-app-iitu',
    storageBucket: 'assistant-app-iitu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVu3MsxaJ0HDcU3RJHPzHXIi1qhN_frgU',
    appId: '1:1098879051348:ios:7383be42e3407d2b4eafc1',
    messagingSenderId: '1098879051348',
    projectId: 'assistant-app-iitu',
    storageBucket: 'assistant-app-iitu.appspot.com',
    iosBundleId: 'com.example.assistantApp',
  );
}
